name: Chromatic PR

on:
  push:
    branches-ignore:
      - renovate/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10.34.4

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm exec nx run-many --all -t build-storybook -- --stats-json

      - uses: chromaui/action@v11
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_ELEMENTS_REACT }}
          exitOnceUploaded: true
          workingDir: packages/elements-react
          storybookBuildDir: storybook-static
          onlyChanged: true
